name: Azure Static Web Apps CI/CD

on:
  push:
    branches-ignore: [development, production]

jobs:
  build_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        id: build
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations ######
          app_location: '/src' # App source code path relative to repository root
